# Generated by Django 4.0.6 on 2022-07-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('last_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('company_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('city', models.CharField(blank=True, max_length=2000, null=True)),
                ('state', models.CharField(blank=True, max_length=2000, null=True)),
                ('zip', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('web', models.URLField(blank=True, db_index=True, max_length=128)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
